### ISSUE TITLE
use of Reagent

### ISSUE THREAD

**Issue by batwicket** [matthiasn/systems-toolbox#18]
The Om Next presentation, https://www.youtube.com/watch?v=ByNs9TG30E8, says that Om is moving towards the Quiescent approach.. a thin layer over Javascript.. because ReactJS is moving to Babel. This means Om Next will be much closer to pure JS.

Reagent, which built on David Nolen's insights, leverages JSX rather than the React API so it may continue to be ok. Facebook is fitting Android and iOS under React so a clean abstraction layer becomes even more useful. I don't see any indication that Facebook is going to abandon JSX.

It's a possible risk so i mention it.

**Comment by matthiasn** [comment]
Actually I've been thinking about using Quiescent for a little while as I don't like the decorated atom approach of Reagent so very much. I also never liked cursors or the complexity of Om previous, so this is going to be very interesting. Luckily, the systems-toolbox is not tied to Om in any way, I can just add a component type for Quiescent now and another one for Om next later.
