### ISSUE TITLE
Add a local state atom and a helper "cmd" function for the UI components

### ISSUE THREAD

**Issue by kamituel** [matthiasn/systems-toolbox#4]
We should have a local state atom for storing transient state such as inputs value, withouth the need of handling that in the global state component. 

Also, we could have a helper `cmd` which would build on top of `put-fn`, so we could write:

`[:button {:on-click (cmd :do-something some-data)}]]`

`cmd` should stop click event propagation, and should put arguments passed to it into a vector and put-fn them.

**Comment by matthiasn** [comment]
Good idea, thanks.
