### ISSUE TITLE
No way to validate an empty message.

### ISSUE THREAD

**Issue by kamituel** [matthiasn/systems-toolbox#49]
Currently, `valid-or-no-spec?` [doesn't warn about missing spec for a command when the message has no payload](https://github.com/matthiasn/systems-toolbox/blob/master/src/cljc/matthiasn/systems_toolbox/spec.cljc#L18).

This means it's not possible to add a spec saying "this message should be empty".  Opening this issue to discuss whether this should be possible.

**Comment by matthiasn** [comment]
Hey @kamituel, thanks, yes I think that would be useful to document the expectation that a message has no payload. I will try out the change in existing projects and get back to you later today. Cheers

**Comment by matthiasn** [comment]
Yup, this is useful, I added it in the latest version. Please have a look and let me know what you think. Cheers

**Comment by matthiasn** [comment]
Closing this for now as there is now support for validating empty messages. Please re-open if there are any further questions, or if it doesn't work for you. Thanks
