### ISSUE TITLE
the :cmp-state doesn't change when had changed the state-fn and restart!

### ISSUE THREAD

**Issue by gzll** [matthiasn/systems-toolbox#50]
I have a component for datomic db, and when I changed the state-fn of the component, then reload the clj files, and ```(require '[cmp] :reload)```, and  restart! the switchboard, but when I used the ``` (:cmp-state (:switchboard-cmp-id (:components @(:cmp-state switchboard)))))```, I get the same thing without change.
I just wonder why?
Now I must restart the repl to make sure work, when I changed the state-fn.

**Comment by gzll** [comment]
Update:
I have read the wire-or-init-comp fn, and think system-toolbox try keep prev-state, So it is its design national.

**Comment by matthiasn** [comment]
Hi @gzll, yes it's supposed to work like that, but would it be useful to introduce some way of resetting component states when reloading? I'm open to suggestions there. Cheers
