### ISSUE TITLE
0.1.30-SNAPSHOT not on Clojars

### ISSUE THREAD

**Issue by davidrupp** [matthiasn/systems-toolbox#6]
Running lein cljsbuild (in examples/trailing-mouse-pointer) results in "(Could not find artifact matthiasn:systems-toolbox:jar:0.1.30-SNAPSHOT in clojars (https://clojars.org/repo/))". I searched manually and the latest version listed is 0.1.25.

**Comment by matthiasn** [comment]
Hi David, you can always run `lein install` from inside the root toolbox directory. I don't really want to publish snapshots, only tagged versions, and that's going to be a day or two until the next one. Let me know if there are any issues with installing it locally (or anything else), happy to help.

**Comment by davidrupp** [comment]
Fair enough. I did not think about lein install; will give that a try. Thanks!
