### ISSUE TITLE
Error when installing master locally

### ISSUE THREAD

**Issue by neverfox** [matthiasn/systems-toolbox#7]
Since this is a SNAPSHOT, I tried bringing this in as a checkout dependency (a symbolic link to a clone of master, lein installed), but I get the following error (that I don't get if I just depend from Clojars).

```
1. Caused by clojure.lang.ExceptionInfo
   Can only recur from tail position
   {:file "matthiasn/systems_toolbox/component.clj",
    :line 59,
    :column 9,
    :exprs nil,
    :form (recur)}
```

**Comment by matthiasn** [comment]
Hmm, this doesn't look familiar. I've never used checkout dependencies though, I just install the library locally.

**Comment by matthiasn** [comment]
Hi, I created the `checkouts` directory locally inside the sample application and the created a symbolic link: `ln -s ../../.. systems-toolbox`
Works fine here and also picks up changes in the library with having to install new version locally. Closing this for now, but feel free to reopen if this doesn't work for you in the latest version.
