### ISSUE TITLE
Reorg toolbox into smaller packages

### ISSUE THREAD

**Issue by neverfox** [matthiasn/systems-toolbox#8]
This is some fantastic work. Any plans to reorganize this project into smaller pieces? As it is, it brings in a whole slew of dependencies that one might not need if they just want to uses the abstract component pattern or the switchboard, for example. This seems like it might be a good candidate for something like [lein-repack](https://github.com/zcaudate/lein-repack).

**Comment by matthiasn** [comment]
That's a great suggestion, I've thought about this before but didn't go deeper yet. I'll look into repack next week, sounds like it could fit the bill. Thanks!

**Comment by matthiasn** [comment]
@neverfox would you like into this? It would be great to have, but I don't have the capacity too dig deeper at the moment. Thanks :-)

**Comment by neverfox** [comment]
I could give it a shot but I'll need to get more familiar with lein-repack myself.

**Comment by matthiasn** [comment]
split into separate libraries altogether
